org: "Boston University"
suborg: "Faculty of Computing & Data Sciences, 1002"
description: >- # this means to ignore newlines until "baseurl:"
domain: "janpaul.pl"
url: "https://janpaul.pl" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
social_tag: janpaulpl
email: janpaul [at] bu [dot] edu
loc: 665 Commonwealth Ave, Boston, MA 02215
orcid_id: "0000-0003-1055-6785"
# Build settings

source: ./
sass:
    sass_dir: assets/css/_sass
    style: compressed
favicon:
  path: assets/img

collections:
  - publications
  - posts
  
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
